meta_product_name: "Consulate of Sweden, Glasgow"
meta_title: "Consulate of Sweden | Glasgow"
meta_description: "We provide consular services for Swedish nationals who are visitors or temporary residents in Glasgow and south west Scotland."
meta_image: "consulate-logo.png" # should exist in `app/assets/images/`
